### ISSUE TITLE
Strange problem when I update User

### ISSUE THREAD

**Issue by liudonghua123** [svlada/springboot-security-jwt#10]
I renamed the `User` to `AdminUser`, `UserRole` to `AdminUserRole`, and add some functionalities like saveOrUpdate on `UserService`, But when I want to update a `AdminUser`, I always got the following exception

```
Column 'admin_user_id' cannot be null
```

```
Hibernate: select adminuser0_.id as id1_0_0_, adminuser0_.password as password2_0_0_, adminuser0_.username as username3_0_0_ from admin_user adminuser0_ where adminuser0_.id=?
Hibernate: update admin_user_role set admin_user_id=null where admin_user_id=?
2017-04-19 15:10:34.759  WARN 7884 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1048, SQLState: 23000
2017-04-19 15:10:34.760 ERROR 7884 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column 'admin_user_id' cannot be null
2017-04-19 15:10:34.760  INFO 7884 --- [nio-8080-exec-1] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2017-04-19 15:10:34.762 ERROR 7884 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'admin_user_id' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
......
```

Here is my modified  `AdminUser`, `AdminUserRole`, `AdminUserService`
```
@Entity
@Table(name="ADMIN_USER")
public class AdminUser {
	
    @Id @Column(name="ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @Column(name="username")
    @NotNull
    private String username;
    
    @Column(name="password")
    @NotNull
    private String password;
    
    @OneToMany
    @JoinColumn(name="ADMIN_USER_ID", referencedColumnName="ID")
    private List<AdminUserRole> roles;
    
    public AdminUser() { }
    
    public AdminUser(Long id, String username, String password, List<AdminUserRole> roles) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.roles = roles;
    }

    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

	public void setUsername(String username) {
		this.username = username;
	}

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<AdminUserRole> getRoles() {
        return roles;
    }

	public void setRoles(List<AdminUserRole> roles) {
		this.roles = roles;
	}
}
```

```
@Entity
@Table(name = "ADMIN_USER_ROLE")
@JsonDeserialize(using = CustomAdminUserRoleDeserializer.class)
public class AdminUserRole {
	
    @EmbeddedId
    private RoleId roleId = new RoleId();
    
    public AdminUserRole() { }
	
    public AdminUserRole(RoleId roleId) {
		this.roleId = roleId;
	}

	public RoleId getRoleId() {
		return roleId;
	}

	public void setRoleId(RoleId roleId) {
		this.roleId = roleId;
	}

	public Role getRole() {
		return roleId.role;
	}

	@Embeddable
    public static class RoleId implements Serializable {
        private static final long serialVersionUID = 1322120000551624359L;
        
        @Column(name = "ADMIN_USER_ID")
        @NotNull
        protected Long userId;
        
        @Enumerated(EnumType.STRING)
        @Column(name = "ROLE", insertable=false, updatable=false)
        @NotNull
        protected Role role;
        
        public RoleId() { }

        public RoleId(Long userId, Role role) {
            this.userId = userId;
            this.role = role;
        }
    }
}
```

```
@Service
public class AdminUserService {

	@Autowired
	private BCryptPasswordEncoder encoder;
	@Autowired
    private AdminUserRepository userRepository;
	@Autowired
    private AdminUserRoleRepository userRoleRepository;
	
    public Optional<AdminUser> getByUsername(String username) {
        return userRepository.findByUsername(username);
    }

	public AdminUser getById(Long id) {
		return userRepository.findOne(id);
	}

	public AdminUser saveOrUpdate(AdminUser adminUser) {
		String rawPassword = adminUser.getPassword();
		String password = encoder.encode(rawPassword);
		adminUser.setPassword(password);
//		userRoleRepository.deleteByRoleId_UserId(adminUser.getId());
		return userRepository.save(adminUser);
	}

	public void delete(Long id) {
		userRepository.delete(id);
	}

	public void delete(AdminUser adminUser) {
		userRepository.delete(adminUser);
	}

	public List<AdminUser> getAll() {
		return userRepository.findAll();
	}
}
```

Any ideas why this happened?

**Comment by liudonghua123** [comment]
It seems like a common problem when using `OneToMany/ManyToOne` with `join column` pattern, I modified using ManyToMany with a join table, now it's worked.
see [spring-data-jpa-delete-child-entities-instead-of-setting-to-null-on-update](http://stackoverflow.com/questions/35143661/spring-data-jpa-delete-child-entities-instead-of-setting-to-null-on-update) [jpa-many-to-many-relationship-mapping-example-with-spring-boot-maven-and-mysql](https://hellokoding.com/jpa-many-to-many-relationship-mapping-example-with-spring-boot-maven-and-mysql/)

AdminUser 
```@Entity
public class AdminUser {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotNull
	private String username;

	@NotNull
	private String password;

	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "admin_user_role_join", joinColumns = @JoinColumn(name = "admin_user_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "admin_user_role_id", referencedColumnName = "id"))
	private List<AdminUserRole> roles;

	public AdminUser() {
	}

	public AdminUser(Long id, String username, String password, List<AdminUserRole> roles) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.roles = roles;
	}

	public Long getId() {
		return id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public List<AdminUserRole> getRoles() {
		return roles;
	}

	public void setRoles(List<AdminUserRole> roles) {
		this.roles = roles;
	}
}
```

AdminUserRole 
```
@Entity
@JsonDeserialize(using = CustomAdminUserRoleDeserializer.class)
public class AdminUserRole {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;

	@Enumerated(EnumType.STRING)
	@NotNull
	protected Role role;

	@ManyToMany(mappedBy = "roles")
	private List<AdminUser> adminUser;

	public AdminUserRole() {
	}

	public AdminUserRole(Long id, Role role) {
		super();
		this.id = id;
		this.role = role;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public List<AdminUser> getAdminUser() {
		return adminUser;
	}

	public void setAdminUser(List<AdminUser> adminUser) {
		this.adminUser = adminUser;
	}
}
```

**Comment by GiridharMG** [comment]
@liudonghua123 What should I do if I get same exception for OneToOne mapping
